# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f219796d78093c856f91b008d06be20fb9836d22af427f08e348da33aea8f4ba534252824893ef405b74ff193a7a92d322089bd16767640eb41fc122313ebe6e

test:
  secret_key_base: ae72c07fdaaa370ed1436b295c4c66c0a540b3545f23bd48585ae9afb26c19687c522a6b589a463cf176ffef41e7a49c99a951ec548000c0a329fb06c7ffd170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
